# Generated by Django 5.1.7 on 2025-04-02 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_word', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Слово должно содержать минимум 2 буквы')], verbose_name='Слово на русском')),
                ('english_word', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Слово должно содержать минимум 2 буквы')], verbose_name='Слово на английском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards_images/', verbose_name='Картинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Карточка английского',
                'verbose_name_plural': 'Карточки английского',
            },
        ),
    ]
