# Generated by Django 5.1.7 on 2025-04-06 14:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=False)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='simulator.englishcard')),
            ],
            options={
                'verbose_name': 'Статистика карточки',
                'verbose_name_plural': 'Статистика карточек',
                'ordering': ['-created_at'],
            },
        ),
    ]
